# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Examples' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'BabyBluetooth', '~> 0.7.0'
  pod 'WebViewJavascriptBridge', '~> 6.0.2'
  pod 'Masonry', '~> 1.0.2'
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'NJKWebViewProgress', '~> 0.2.3'
  pod 'YYModel', '~> 1.0.4'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'Reachability', '~> 3.2'
  pod 'HardwareDatasStorage', '~> 0.0.1'

  # Pods for Examples

end
