# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Examples' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'YDBluetoothWebBridge', '~> 0.2.5'
  # Pods for Examples

end
